name: Python application

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install root dependencies
        pip install -r requirements.txt
        # Install API dependencies
        pip install -r api_app/requirements.txt
        # Install web app dependencies
        pip install -r web_app/requirements.txt

    - name: Verify installation
      run: |
        python --version
        pip list
        echo "✅ Dependencies installed successfully"

    - name: Basic syntax check
      run: |
        python -m py_compile simple_fresh_webapp.py
        python -m py_compile api_app/api_server.py
        python -m py_compile web_app/web_app.py
        echo "✅ All Python files compile successfully"