name: Python application

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests selenium webdriver-manager

    - name: Run API tests
      run: pytest tests/test_api_ytd.py

    - name: Run Selenium tests (headless)
      run: pytest -s tests/test_webapp_selenium.py