name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests selenium

    - name: Run API tests
      run: pytest tests/test_api_ytd.py

    - name: Run Selenium tests (headless)
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-driver
        pytest tests/test_webapp_selenium.py
      env:
        # Set this if your Selenium tests need to run Chrome in headless mode
        # (add this to your get_driver() if needed)
        # Example: os.environ["HEADLESS"] = "1"
        DISPLAY: ":99"